
Vagrant.configure("2") do |config|
   config.vm.hostname = "mongodb"
   config.vm.network "private_network", ip: "192.168.33.27"
   config.vm.provider 'virtualbox' do |vb|
    vb.memory = 1024
  end

  config.vm.provision :shell, path: 'mongodb.sh'
end