# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |ubuntu|
		ubuntu.vm.hostname = "elasticnode1"
		ubuntu.vm.network "private_network", ip: "192.168.33.21"
        ubuntu.vm.box = "ubuntu/bionic64"
        ubuntu.vm.network :forwarded_port, guest: 9201, host: 9201
        ubuntu.vm.provision :shell, :path => "../java_install.sh"
		ubuntu.vm.synced_folder ".", "/home/vagrant/data", nfs:true
        ubuntu.vm.provider :virtualbox do |v|
            v.name = "ubuntu_elasticsearch_1"
			v.memory = 2048
    end
end
