# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "private_network", ip: "192.168.33.11"
    config.vm.network :forwarded_port, guest: 80, host: 80
    config.vm.hostname = "bionicBeaver2"
    config.vm.box_version = "20190327.0.0"
    config.ssh.insert_key = true
    config.vm.synced_folder ".", "/var/www/open-security-check", nfs:true
    config.vm.provider "virtualbox" do |vb|
        vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/var/www", "1"]
    end
end
